<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\IncidentIntelligence.Application\IncidentIntelligence.Application.csproj" />
    <ProjectReference Include="..\IncidentIntelligence.Domain\IncidentIntelligence.Domain.csproj" />
  </ItemGroup>

</Project>
